theme = "nord"

[editor]
line-number = "relative"
cursorline = true
rulers = [80]
bufferline = "multiple"

[keys.normal]
t = "move_char_left"
s = "move_visual_line_down"
r = "move_visual_line_up"
n = "move_char_right"
"’" = "select_regex"
h = "change_selection"

[keys.normal."space"]
"F" = "file_picker_in_current_buffer_directory"
