[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "python"
language-servers = [ { name = "pylsp", except-features = [ "format" ] }, "ruff"]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
ruff.enabled = false
autopep8.enabled = false
flake8.enabled = false
mccabe.enabled = false
pycodestyle.enabled = false
pyflakes.enabled = false
pylint.enabled = false
yapf.enabled = false

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]

[[languages]]
name = "go"
injection-regex = "go"
auto-format = true
formatter = { command = "goimports", args = [ "-w" ] }
language-server = { command = "gopls" }

[language-server.gopls]
command = "gopls"

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[[language]]
name = "sql"
language-servers = [ "sql-language-server" ]

[[language]]
name = "nix"
formatter = { command = "nixpkgs-fmt" }

[language-server]
jdtls = { command = "jdtls" }
language-server = { command = "jdtls", args = [
  "-data", "/home/<USER>/.cache/jdtls/workspace"
  ]}

[[language]]
name = "java"
scope = "source.java"
injection-regex = "java"
file-types = ["java"]
roots = ["pom.xml", "build.gradle", ]
indent = { tab-width = 4, unit = "    " }
language-servers = [ "jdtls" ]
